;SIMPLE INPUT OUTPUT PROGRAM
.MODEL SMALL
.STACK 100H

.CODE

MAIN PROC

    MOV AH,1 ; INPUT FUNCTION
    INT 21H ;INTERRUPT
    MOV BL,AL ; PUTTING INPUT INFO BL FOR OUTPUT

    MOV AH,2 ;OUTPUT FUNCTION
    MOV DL,BL ;OUTPUT
    INT 21H ;INTERRUPT

END MAIN